spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: "/openapi"
  swagger-ui:
    disable-swagger-default-url: true
    show-common-extensions: true
    operations-sorter: "alpha"
    path: "/docs/"

server:
  error:
    whitelabel:
      enabled: false
